<a href="https://colab.research.google.com/github/parth-4895/Machine-Learning/blob/main/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [4]:
#arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [30]:
#reshape
a1 = np.arange(8).reshape(2,2,2)
a2=np.arange(1,51).reshape(2,5,5)
print("a1: " ,a1,"\n\na2:",a2)


a1:  [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 

a2: [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]

 [[26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]


In [15]:
#random
a1=np.random.random((3,4,2))
a2=np.random.random((3,2))
print("a1: " ,a1,"\n\na2:",a2)

a1:  [[[0.41276984 0.62806932]
  [0.91604846 0.18952592]
  [0.86076953 0.07312517]
  [0.33496958 0.59327543]]

 [[0.7658934  0.41924702]
  [0.3567368  0.96461012]
  [0.02589895 0.86527189]
  [0.2272983  0.65240815]]

 [[0.86594385 0.17835487]
  [0.28766739 0.66348894]
  [0.37344423 0.14408165]
  [0.09137889 0.74840092]]] 

a2: [[0.3472368  0.92624164]
 [0.67371759 0.84167983]
 [0.2762752  0.35718838]]


In [39]:
#linspace to divide the space into the given number of equally spaced numbers or
#to the atmost precision by default
a1= np.linspace(1,10)
a2 = np.linspace(1,10,5)

print("a1: " ,a1,"\n\na2:",a2)

a1:  [ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ] 

a2: [ 1.    3.25  5.5   7.75 10.  ]


In [41]:
#ndim to tell the dimensions
an=a1.reshape(2,5,5)
an.ndim


3

In [43]:
#shape
an.shape

(2, 5, 5)

In [47]:
#size for the number of items
a1.shape , an.size

((50,), 50)

In [48]:
#itemsize to tell the size of the datatype

In [50]:
#dtype to tell the datatype of a variable
print(a1.dtype)
p = np.arange(1,50,2, dtype ="int32")
print(p.dtype)
q= np.array([[1,2,5,8],[10,9,50,23]])
print(q.dtype)

float64
int32
int64


# Changing Datatypes

In [59]:
#astype to change the datatype. Needs to be stored
print(a1.dtype)
a2 = a1.astype(np.int32)
print("a1: " ,a1,"\n\na2:",a2)

float64
a1:  [ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ] 

a2: [ 1  1  1  1  1  1  2  2  2  2  2  3  3  3  3  3  3  4  4  4  4  4  5  5
  5  5  5  5  6  6  6  6  6  7  7  7  7  7  7  8  8  8  8  8  9  9  9  9
  9 10]


# Array Operations

In [61]:
#vector-scaler arithmetic operations
print(a1+2)
print(a1-2)
print(a1*2)
print(a1/2)
print(a1**2)

[ 3.          3.18367347  3.36734694  3.55102041  3.73469388  3.91836735
  4.10204082  4.28571429  4.46938776  4.65306122  4.83673469  5.02040816
  5.20408163  5.3877551   5.57142857  5.75510204  5.93877551  6.12244898
  6.30612245  6.48979592  6.67346939  6.85714286  7.04081633  7.2244898
  7.40816327  7.59183673  7.7755102   7.95918367  8.14285714  8.32653061
  8.51020408  8.69387755  8.87755102  9.06122449  9.24489796  9.42857143
  9.6122449   9.79591837  9.97959184 10.16326531 10.34693878 10.53061224
 10.71428571 10.89795918 11.08163265 11.26530612 11.44897959 11.63265306
 11.81632653 12.        ]
[-1.         -0.81632653 -0.63265306 -0.44897959 -0.26530612 -0.08163265
  0.10204082  0.28571429  0.46938776  0.65306122  0.83673469  1.02040816
  1.20408163  1.3877551   1.57142857  1.75510204  1.93877551  2.12244898
  2.30612245  2.48979592  2.67346939  2.85714286  3.04081633  3.2244898
  3.40816327  3.59183673  3.7755102   3.95918367  4.14285714  4.32653061
  4.51020408  4.69387755  4

In [62]:
#vector-vector operations. This is possible here as the vectors have the same size
a2 = a1*9 - 33
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1**a2)

[-23.         -21.16326531 -19.32653061 -17.48979592 -15.65306122
 -13.81632653 -11.97959184 -10.14285714  -8.30612245  -6.46938776
  -4.63265306  -2.79591837  -0.95918367   0.87755102   2.71428571
   4.55102041   6.3877551    8.2244898   10.06122449  11.89795918
  13.73469388  15.57142857  17.40816327  19.24489796  21.08163265
  22.91836735  24.75510204  26.59183673  28.42857143  30.26530612
  32.10204082  33.93877551  35.7755102   37.6122449   39.44897959
  41.28571429  43.12244898  44.95918367  46.79591837  48.63265306
  50.46938776  52.30612245  54.14285714  55.97959184  57.81632653
  59.65306122  61.48979592  63.32653061  65.16326531  67.        ]
[ 2.50000000e+01  2.35306122e+01  2.20612245e+01  2.05918367e+01
  1.91224490e+01  1.76530612e+01  1.61836735e+01  1.47142857e+01
  1.32448980e+01  1.17755102e+01  1.03061224e+01  8.83673469e+00
  7.36734694e+00  5.89795918e+00  4.42857143e+00  2.95918367e+00
  1.48979592e+00  2.04081633e-02 -1.44897959e+00 -2.91836735e+00
 -4.38775510e+

In [66]:
#relational
print(a1>5)
print(a2<0)
print(a1>a2)

[False False False False False False False False False False False False
 False False False False False False False False False False  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False]


# Array Functions Mathematical

In [69]:
a1 = np.random.random((3,3))
a1= np.round(a1*100)
a1

array([[25., 73., 98.],
       [33., 54., 21.],
       [10., 81., 25.]])

In [75]:
#max/min/sum/prod
# 0->column 1->row
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))
print(np.max(a1, axis=1))#max of each row?
print(np.min(a1,axis = 1)) # min of each row?
print(np.sum(a1, axis = 0)) #sum of each column
print(np.prod(a1, axis = 0)) #prod of each column


98.0
10.0
420.0
135531725175000.0
[98. 54. 81.]
[25. 21. 10.]
[ 68. 208. 144.]
[  8250. 319302.  51450.]


In [78]:
#mean/median/std/var
np.mean(a1, axis = 1) #same for all the other functions

array([65.33333333, 36.        , 38.66666667])

In [79]:
#trigonometric functions (mostly never used in data science career)
np.sin(a1)

array([[-0.13235175, -0.67677196, -0.57338187],
       [ 0.99991186, -0.55878905,  0.83665564],
       [-0.54402111, -0.62988799, -0.13235175]])

In [81]:
#dot product
a2 = np.arange(1,13).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[180, 190, 200],
       [444, 470, 496],
       [708, 750, 792]])

In [82]:
#log and exponents
np.log(a1)

array([[3.21887582, 4.29045944, 4.58496748],
       [3.49650756, 3.98898405, 3.04452244],
       [2.30258509, 4.39444915, 3.21887582]])

In [83]:
np.exp(a1)

array([[7.20048993e+10, 5.05239363e+31, 3.63797095e+42],
       [2.14643580e+14, 2.83075330e+23, 1.31881573e+09],
       [2.20264658e+04, 1.50609731e+35, 7.20048993e+10]])

In [87]:
#round/floor/ceil
a4 = np.random.random((2,3))*100
np.round(a4)

array([[73., 92., 14.],
       [33., 11., 12.]])

In [88]:
np.ceil(a4)

array([[74., 92., 14.],
       [33., 11., 12.]])

In [90]:
np.floor(a4)

array([[73., 91., 13.],
       [32., 10., 11.]])

# Indexing and Slicing

In [94]:
a1 = np.arange(1,11)
a2 = np.arange(1,51).reshape(2,25)
a3 = np.arange(1,51).reshape(2,5,5)

In [95]:
#indexing simple as it is normally. Fetching a number from an array using the index

In [96]:
#slicing
a1[2:5] #all indexes [2,5)

array([3, 4, 5])

In [105]:
a1[2:8:2] # the last index gives the number of variables to leave

array([3, 5, 7])

In [115]:
a2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [118]:
a2[0:2, 3:6] #a2[rows, col]

array([[ 4,  5,  6],
       [29, 30, 31]])

In [120]:
a4 = np.arange(0,12).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
# now to fetch the values, 0,3,8,11
a4[::2, ::3] # the double colons ::x means that all rows/cols with x jumps

array([[ 0,  3],
       [ 8, 11]])

In [123]:
a4[::2, 1:5:2]

array([[ 1,  3],
       [ 9, 11]])

In [124]:
# OR
a4[::2 , 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [109]:
a3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]],

       [[26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50]]])

In [114]:
a3[0:2, 0:2, 0:2] # a3[the 2 dim arr, the rows of the one dim arr, the col of the one dim arr]

array([[[ 1,  2],
        [ 6,  7]],

       [[26, 27],
        [31, 32]]])

In [125]:
a3[::2]

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]])

In [132]:
a5 = np.arange(0,27).reshape(3,3,3)
a5

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [133]:
a5[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [134]:
a5[0,1,:]

array([3, 4, 5])

In [135]:
a5[1, : , 1]

array([10, 13, 16])

In [136]:
a5[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [140]:
a5[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

In [141]:
a5[::2, ::2, ::2]

array([[[ 0,  2],
        [ 6,  8]],

       [[18, 20],
        [24, 26]]])

In [143]:
a5[::2, :2, ::2]

array([[[ 0,  2],
        [ 3,  5]],

       [[18, 20],
        [21, 23]]])